#!/usr/bin/env zsh

# XDG Base Directories (https://wiki.archlinux.org/title/XDG_Base_Directory)
export XDG_CONFIG_HOME="$HOME/.config"
export XDG_DATA_HOME="$XDG_CONFIG_HOME/local/share"
export XDG_CACHE_HOME="$XDG_CONFIG_HOME/cache"

# default text editors
export EDITOR="vim"
export VISUAL="vim"

# default zsh configuration variables
export ZDOTDIR="$XDG_CONFIG_HOME/zsh"

export HISTFILE="$ZDOTDIR/.zhistory"
export HISTSIZE=10000
export SAVEHIST=10000

# add godev to path
export PATH="$PATH:$HOME/go/godev/bin"
